### ISSUE TITLE
npm package vulnerabilities

### ISSUE THREAD

**Issue by aspdotnut** [curio-team/sdlogin#38]
There are 162 npm package vulnerabilities: 5 low, 77 moderate, 55 high, 25 critical.

Some of these have to do with XSS and command injection.
I'd recommend running `npm audit fix` to fix most of these, and if possible review the breaking changes and updating those too.

**Comment by luttje** [comment]
Good catch. We'll investigate if we're actually using this package, or some other version of it.

Thanks for the heads-up
