### ISSUE TITLE
Redirect is lost after incorrect login

### ISSUE THREAD

**Issue by luttje** [curio-team/sdlogin#39]
Steps to reproduce:
1. Go to client application
2. Click 'Login'
3. You're sent to amologin
4. Enter an incorrect password logging in
5. You're sent back to amologin
6. Now enter the correct password
7. You're sent to the curio.codes homepage instead of the redirect url that was provided with the initial request

This problem does not occur when entering the correct password right away.

**Comment by luttje** [comment]
Might have been fixed when updating Laravel Passport. Looking at the code I think maybe adding this line is what fixed it: https://github.com/curio-team/sdlogin/blob/8321239942b640f686214d48c046dca5882b60b6/app/Http/Controllers/ClientController.php#L21

Would love if someone could confirm this is still a problem once we go live with the new version.

**Comment by bartjroos** [comment]
Seems okay now!
