### ISSUE TITLE
Test project functionality

### ISSUE THREAD

**Issue by luttje** [curio-team/sdlogin#41]
Taken from #40:

- [x] Test everything manually

Nice to haves:
- [x] Write some automated tests

**Comment by bartjroos** [comment]
Tested the main lifecycle of;

- Batch-creating groups
- Importing users
- Importing same users again with different group
- Resetting passwords for entire group
- Group expires
- Cleanup users without active groups

Will test creating an app later, when I get to work on the Weeks-api. Will update Weeks-api to use sdclient and test everyting locally.

**Comment by bartjroos** [comment]
Tested creating an app and loging in with sd-client, al localy
