### ISSUE TITLE
Organize deployment of production environment

### ISSUE THREAD

**Issue by luttje** [curio-team/sdlogin#42]
Taken from #40 

- [x] Back-up old database
- [x] Perform local test update
- [x] Check if the server has PHP 8.2+
- [x] Find a time to roll-out the update

Unrelated to this, but related to the `sdclient` package:
- [x] Update all our projects that depend on amoclient to sdclient (like done here: https://github.com/curio-team/narrowblast/pull/14) - so they're on the [curio packagist](https://packagist.org/packages/curio/)

**Comment by bartjroos** [comment]
Server is still running php 7.0 on ubuntu 16.04.

Might be easer to spin up a new server based on the latest template, run this for a while under something like `nieuw.login.curio.codes` and when the time comes, we'll point the current subdomain to that new servers ip.

Updating the current server would probably be quite a hassle, and would likely even break the current loginservice; giving us no time to slowly migrate.

**Comment by bartjroos** [comment]
- [ ] Set-up e-mails on the new server/application (_or maybe just rip this out and have students always ask a teacher to reset password... this would need a more dedicated page/button_)

**Comment by bartjroos** [comment]
- [ ] This would also allow for testing the shortlinks / redirector functionality on the actual domains

**Comment by luttje** [comment]
> * [ ]  Set-up e-mails on the new server/application (_or maybe just rip this out and have students always ask a teacher to reset password... this would need a more dedicated page/button_)

In order to not land in spam we need a domain that does not contain 'curio'. I believe phishing filters block curio.codes

**Comment by luttje** [comment]
I've made some changes with regards to the password resetting. Teachers can now force users to reset their password after they've changed it for them (default). Additionally I removed the password complexity restriction for admins, so they can set a simpler temporary password.

I'll move this into production in 2 weeks when we move to login2

**Comment by luttje** [comment]
FYI: Didn't manage to move this into production during the recent vacation. Will have to wait till end of the school year
