### ISSUE TITLE
Fix edictis import 

### ISSUE THREAD

**Issue by luttje** [curio-team/sdlogin#43]
Taken from #40:

Fix edictis import 

Do we use this @bartjroos?

**Comment by bartjroos** [comment]
Nope! This can be deprecated, only eol import still in use


Met vriendelijke groet,
Bart Roos
Docent
Curio techniek en technologie
Terheijdenseweg 350 | 4826 AA Breda
T 088 209 9223
***@***.***
Op 2 mrt 2024 om 10:15 heeft luttje ***@***.***> het volgende geschreven:

﻿
U ontvangt niet vaak e-mail van ***@***.*** Meer informatie over waarom dit belangrijk is<https://aka.ms/LearnAboutSenderIdentification>

Taken from #40<https://github.com/curio-team/sdlogin/pull/40>:

Fix edictis import

Do we use this @bartjroos<https://github.com/bartjroos>?

**Comment by luttje** [comment]
Awesome, thanks!
